using Antiphon.SessionRunner;
using Antiphon.SessionRunner.Contracts;
using Shouldly;
using TUnit.Core;

namespace Antiphon.Tests.Agents;

/// <summary>
/// Verifies the Claude Code JSONL transcript normalizer against the real record shapes observed in a
/// live session (assistant text/thinking/tool_use, stop_reason, user string prompts, tool_result blocks,
/// ai-title, isMeta).
/// </summary>
public class TranscriptNormalizerTests
{
    // The compact-boundary fixture is the single source of truth for the record shape (captured
    // from real claude by ClaudeCompactionCanaryTests; fakeclaude mirrors it).
    private static string CompactBoundaryFixtureLine() =>
        File.ReadLines(Path.Combine(AppContext.BaseDirectory, "Agents", "Fixtures", "compact-boundary.jsonl"))
            .First(l => !string.IsNullOrWhiteSpace(l));

    [Test]
    public void Compact_boundary_line_normalizes_to_CompactBoundary_kind()
    {
        var parts = TranscriptNormalizer.Normalize(CompactBoundaryFixtureLine());

        var part = parts.ShouldHaveSingleItem();
        part.Kind.ShouldBe(TranscriptKinds.CompactBoundary);
        part.Text.ShouldBe("Context compacted (manual)");
        part.Uuid.ShouldNotBeNull();
        part.Timestamp.ShouldNotBeNull();
    }

    // At the NORMALIZER level only: no TurnEnd part, no StopReason. The working/idle rules DO rank
    // a manual boundary as a turn end (CARD-0041) — they key on the "(manual)" trigger in the text
    // pinned above, not on a stop reason. Both statements are true and neither replaces the other.
    [Test]
    public void Compact_boundary_is_not_a_turn_end()
    {
        var parts = TranscriptNormalizer.Normalize(CompactBoundaryFixtureLine());

        parts.ShouldNotContain(p => p.Kind == TranscriptKinds.TurnEnd);
        parts.Single().StopReason.ShouldBeNull();
    }

    // CARD-0041: the working rules read the TRIGGER out of the boundary's normalized text, so the
    // normalizer↔rule seam is load-bearing in both directions — a boundary that lost its trigger
    // would silently stop ending turns, and an auto boundary that gained "(manual)" would end them
    // when it must not. The fixture is the manual one; the auto shape is asserted alongside.
    [Test]
    public void Manual_and_auto_boundaries_are_distinguishable_by_the_working_rules()
    {
        var manual = TranscriptNormalizer.Normalize(CompactBoundaryFixtureLine()).ShouldHaveSingleItem();
        TranscriptKinds.IsManualCompactBoundary(manual.Kind, manual.Text).ShouldBeTrue();

        const string autoLine =
            """{"type":"system","subtype":"compact_boundary","uuid":"u-auto","timestamp":"2026-08-11T10:54:04.124Z","compactMetadata":{"trigger":"auto","preTokens":1000,"postTokens":100}}""";
        var auto = TranscriptNormalizer.Normalize(autoLine).ShouldHaveSingleItem();
        auto.Text.ShouldBe("Context compacted (auto)");
        TranscriptKinds.IsManualCompactBoundary(auto.Kind, auto.Text)
            .ShouldBeFalse("an auto compaction lands MID-turn — it must never rank as a turn end");
    }

    // The other half of CARD-0041: compaction's synthetic continuation record. It normalizes to a
    // plain UserPrompt (nothing structural survives), which is exactly why the rule matches by text.
    [Test]
    public void Compaction_continuation_record_normalizes_to_an_excludable_user_prompt()
    {
        const string line =
            """{"type":"user","uuid":"u-cont","timestamp":"2026-08-11T10:53:54.816Z","isCompactSummary":true,"message":{"role":"user","content":"This session is being continued from a previous conversation that ran out of context. The conversation is summarized below:\nAnalysis: ..."}}""";

        var part = TranscriptNormalizer.Normalize(line).ShouldHaveSingleItem();
        part.Kind.ShouldBe(TranscriptKinds.UserPrompt);
        TranscriptKinds.IsCompactionContinuationPrompt(part.Kind, part.Text).ShouldBeTrue();
    }

    // The caveat record compaction writes alongside the command wrapper: isMeta, so it is dropped
    // here and never reaches a working rule at all (which is why no rule mentions it).
    [Test]
    public void Compaction_caveat_meta_record_is_dropped()
    {
        const string line =
            """{"type":"user","uuid":"u-caveat","isMeta":true,"message":{"role":"user","content":"Caveat: The messages below were generated by the user while running local commands."}}""";

        TranscriptNormalizer.Normalize(line).ShouldBeEmpty();
    }

    // The two verbatim JSONL lines of ONE API response: session 7f9d06a5 (task ff320d72),
    // msg_011Ce2Xog1xCJs9P, whose thinking record is stamped 11:05:43 and whose 5 850-char report is
    // stamped 11:06:01 — written to the file together at the end of the response.
    private static string[] SplitFinalResponseFixtureLines() =>
        File.ReadLines(Path.Combine(AppContext.BaseDirectory, "Agents", "Fixtures", "split-final-response.jsonl"))
            .Where(l => !string.IsNullOrWhiteSpace(l))
            .ToArray();

    /// <summary>
    /// The shape the whole of CARD-0046 rests on. A thinking record whose <c>thinking</c> string is
    /// EMPTY (signature only — true of all 1 936 thinking blocks measured on this machine) produces
    /// no Thinking part, so the record yields exactly ONE part: a bare <c>TurnEnd</c>. It carries the
    /// response's ApiCallId, and that is the only handle anything has on "is this response finished
    /// speaking?".
    ///
    /// If this ever produced a Thinking part as well, the DB would hold Thinking rows (it holds
    /// zero against 1 366 TurnEnd rows) and settlement's same-id check would have to change with it.
    /// </summary>
    [Test]
    public void A_signature_only_thinking_record_yields_exactly_one_bare_turn_end()
    {
        var part = TranscriptNormalizer.Normalize(SplitFinalResponseFixtureLines()[0]).ShouldHaveSingleItem();

        part.Kind.ShouldBe(TranscriptKinds.TurnEnd);
        part.StopReason.ShouldBe("end_turn");
        part.Text.ShouldBeNull("there is no text on this record — which is exactly the problem");
        part.ApiCallId.ShouldNotBeNull("the id is what identifies the response that ended the turn");
    }

    /// <summary>
    /// And the second record of the same response: the report, plus its OWN TurnEnd (every record of
    /// the response carries the stop_reason). All three parts share one message.id — the identity
    /// settlement now waits on, and the reason the acted-on boundary is always the earlier bare one.
    /// </summary>
    [Test]
    public void Both_records_of_one_response_carry_its_stop_reason_and_its_id()
    {
        var lines = SplitFinalResponseFixtureLines();
        lines.Length.ShouldBe(2);

        var parts = lines.SelectMany(TranscriptNormalizer.Normalize).ToList();

        var text = parts.Where(p => p.Kind == TranscriptKinds.AssistantText).ShouldHaveSingleItem();
        text.Text!.Length.ShouldBe(5_850, "the report that was discarded, verbatim");
        parts.Count(p => p.Kind == TranscriptKinds.TurnEnd)
            .ShouldBe(2, "the thinking record announces the end; the text record repeats it");
        parts.ShouldAllBe(p => p.ApiCallId == text.ApiCallId);
    }

    // Verbatim real records (CARD-0072 sweep): one line per measured error/status combination,
    // line 0 being the exact wall stub that killed delegate task ee0a18a5 on 2026-08-17, plus the
    // benign "No response requested." synthetic (isApiErrorMessage:FALSE) as the negative §6.6
    // pins — a collision between the benign shape and the stub flag must fail loudly here.
    private static string[] ApiErrorFixtureLines() =>
        File.ReadLines(Path.Combine(AppContext.BaseDirectory, "Agents", "Fixtures", "api-error-stubs.jsonl"))
            .Where(l => !string.IsNullOrWhiteSpace(l))
            .ToArray();

    /// <summary>
    /// The S1 carriage itself (CARD-0072): a wall stub's top-level error/isApiErrorMessage/
    /// apiErrorStatus — discarded entirely before this change — land on BOTH of the stub's parts.
    /// The stub also carries its own ordinary TurnEnd, which is why detection is a consumer-side
    /// predicate and no working/idle rule changes: the session already reads idle.
    /// </summary>
    [Test]
    public void A_wall_stub_stamps_the_api_error_fields_on_both_its_parts()
    {
        var parts = TranscriptNormalizer.Normalize(ApiErrorFixtureLines()[0]);

        parts.Count.ShouldBe(2);
        parts[0].Kind.ShouldBe(TranscriptKinds.AssistantText);
        parts[0].Text.ShouldBe("You've hit your session limit · resets 6:10pm (Europe/London)");
        parts[1].Kind.ShouldBe(TranscriptKinds.TurnEnd);
        parts[1].StopReason.ShouldBe("stop_sequence", "the stub ends its turn like any other record");
        foreach (var part in parts)
        {
            part.IsApiError.ShouldBe(true);
            part.ApiErrorClass.ShouldBe("rate_limit");
            part.ApiErrorStatus.ShouldBe(429);
            TranscriptKinds.IsApiErrorStub(part.Kind, part.IsApiError).ShouldBeTrue();
        }
    }

    // Each measured class, verbatim: the status is OPTIONAL on the real records (auth and the
    // connection drop carry none), so null status must survive the carriage as null, not 0.
    [Test]
    public void Every_measured_stub_class_carries_its_fields_and_trips_the_predicate()
    {
        var lines = ApiErrorFixtureLines();
        var expected = new (string Class, int? Status)[]
        {
            ("rate_limit", 429),
            ("server_error", 529),
            ("server_error", null), // connection drop
            ("authentication_failed", null),
            ("model_not_found", 404),
        };

        for (var i = 0; i < expected.Length; i++)
        {
            var text = TranscriptNormalizer.Normalize(lines[i])
                .Where(p => p.Kind == TranscriptKinds.AssistantText)
                .ShouldHaveSingleItem($"fixture line {i}");
            text.IsApiError.ShouldBe(true, $"fixture line {i}");
            text.ApiErrorClass.ShouldBe(expected[i].Class, $"fixture line {i}");
            text.ApiErrorStatus.ShouldBe(expected[i].Status, $"fixture line {i}");
            TranscriptKinds.IsApiErrorStub(text.Kind, text.IsApiError).ShouldBeTrue($"fixture line {i}");
        }
    }

    /// <summary>
    /// The benign synthetic (§6.6's assumed-disjoint shape, pinned as a negative): it shares the
    /// stub's synthetic model and stop_sequence but carries <c>isApiErrorMessage:FALSE</c> and no
    /// error — so the raw false is carried (not laundered to null) and the predicate stays cold.
    /// This is also why stop_reason was rejected as the signal: this record would trip it.
    /// </summary>
    [Test]
    public void The_benign_no_response_synthetic_is_not_a_stub()
    {
        var parts = TranscriptNormalizer.Normalize(ApiErrorFixtureLines()[5]);

        var text = parts.Where(p => p.Kind == TranscriptKinds.AssistantText).ShouldHaveSingleItem();
        text.Text.ShouldBe("No response requested.");
        text.IsApiError.ShouldBe(false);
        text.ApiErrorClass.ShouldBeNull();
        text.ApiErrorStatus.ShouldBeNull();
        parts.ShouldAllBe(p => !TranscriptKinds.IsApiErrorStub(p.Kind, p.IsApiError));
    }

    // Text matching is REJECTED as the signal (spec §D1): an agent legitimately writing about
    // these errors — as the spec itself does — must never trip detection. An ordinary assistant
    // record whose text IS the limit message has no stub fields, and stays invisible.
    [Test]
    public void An_agent_merely_writing_the_limit_message_never_trips_the_predicate()
    {
        const string line =
            """{"type":"assistant","uuid":"u-talk","message":{"role":"assistant","stop_reason":"end_turn","content":[{"type":"text","text":"You've hit your session limit · resets 6:10pm (Europe/London) — that is the stub text this spec is about."}]}}""";

        var parts = TranscriptNormalizer.Normalize(line);

        parts.Count.ShouldBe(2);
        foreach (var part in parts)
        {
            part.IsApiError.ShouldBeNull("an ordinary record never carried the flag");
            TranscriptKinds.IsApiErrorStub(part.Kind, part.IsApiError).ShouldBeFalse();
        }
    }

    // The predicate is structural in BOTH directions: the flag without a stub-bearing kind (a
    // hypothetical flagged UserPrompt) is not a stub row either.
    [Test]
    public void The_predicate_requires_a_stub_bearing_kind()
    {
        TranscriptKinds.IsApiErrorStub(TranscriptKinds.AssistantText, true).ShouldBeTrue();
        TranscriptKinds.IsApiErrorStub(TranscriptKinds.TurnEnd, true).ShouldBeTrue();
        TranscriptKinds.IsApiErrorStub(TranscriptKinds.UserPrompt, true).ShouldBeFalse();
        TranscriptKinds.IsApiErrorStub(TranscriptKinds.AssistantText, false).ShouldBeFalse();
        TranscriptKinds.IsApiErrorStub(TranscriptKinds.AssistantText, null).ShouldBeFalse();
        TranscriptKinds.IsApiErrorStub(null, true).ShouldBeFalse();
    }

    [Test]
    public void Other_system_records_are_still_skipped()
    {
        const string line = """{"type":"system","subtype":"info","content":"something else","uuid":"u9"}""";
        TranscriptNormalizer.Normalize(line).ShouldBeEmpty();
    }

    [Test]
    public void Assistant_text_plus_tool_use_with_tool_use_stop_reason_yields_no_turn_end()
    {
        const string line = """{"type":"assistant","uuid":"u1","parentUuid":"p0","timestamp":"2026-06-11T21:23:32.934Z","message":{"role":"assistant","model":"claude-opus-4-8","stop_reason":"tool_use","content":[{"type":"text","text":"Let me check."},{"type":"tool_use","id":"toolu_1","name":"Bash","input":{"command":"npm run dev"}}]}}""";

        var parts = TranscriptNormalizer.Normalize(line);

        parts.Count.ShouldBe(2);
        parts[0].Kind.ShouldBe(TranscriptKinds.AssistantText);
        parts[0].Text.ShouldBe("Let me check.");
        parts[0].Uuid.ShouldBe("u1");
        parts[1].Kind.ShouldBe(TranscriptKinds.ToolCall);
        parts[1].ToolName.ShouldBe("Bash");
        parts[1].ToolUseId.ShouldBe("toolu_1");
        parts[1].ToolInput.ShouldNotBeNull();
        parts[1].ToolInput!.ShouldContain("npm run dev");
        parts.ShouldNotContain(p => p.Kind == TranscriptKinds.TurnEnd);
    }

    [Test]
    public void Assistant_end_turn_emits_turn_end_marker()
    {
        const string line = """{"type":"assistant","uuid":"u2","message":{"role":"assistant","stop_reason":"end_turn","content":[{"type":"text","text":"Committed and pushed."}]}}""";

        var parts = TranscriptNormalizer.Normalize(line);

        parts.Count.ShouldBe(2);
        parts[0].Kind.ShouldBe(TranscriptKinds.AssistantText);
        parts[1].Kind.ShouldBe(TranscriptKinds.TurnEnd);
        parts[1].StopReason.ShouldBe("end_turn");
    }

    [Test]
    public void Assistant_thinking_block_is_captured()
    {
        const string line = """{"type":"assistant","message":{"role":"assistant","stop_reason":"tool_use","content":[{"type":"thinking","thinking":"weighing options"}]}}""";

        var parts = TranscriptNormalizer.Normalize(line);

        parts.Count.ShouldBe(1);
        parts[0].Kind.ShouldBe(TranscriptKinds.Thinking);
        parts[0].Text.ShouldBe("weighing options");
    }

    [Test]
    public void User_string_content_is_a_prompt()
    {
        const string line = """{"type":"user","message":{"role":"user","content":"run the app"}}""";

        var parts = TranscriptNormalizer.Normalize(line);

        parts.Count.ShouldBe(1);
        parts[0].Kind.ShouldBe(TranscriptKinds.UserPrompt);
        parts[0].Text.ShouldBe("run the app");
    }

    [Test]
    public void User_tool_result_is_extracted_with_error_flag()
    {
        const string line = """{"type":"user","message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"toolu_1","is_error":true,"content":"boom"}]}}""";

        var parts = TranscriptNormalizer.Normalize(line);

        parts.Count.ShouldBe(1);
        parts[0].Kind.ShouldBe(TranscriptKinds.ToolResult);
        parts[0].ToolUseId.ShouldBe("toolu_1");
        parts[0].ToolIsError.ShouldBe(true);
        parts[0].Text.ShouldBe("boom");
    }

    [Test]
    public void Ai_title_becomes_turn_title()
    {
        const string line = """{"type":"ai-title","aiTitle":"Run the app"}""";

        var parts = TranscriptNormalizer.Normalize(line);

        parts.Count.ShouldBe(1);
        parts[0].Kind.ShouldBe(TranscriptKinds.TurnTitle);
        parts[0].Text.ShouldBe("Run the app");
    }

    [Test]
    public void Assistant_usage_and_message_id_are_attached_to_every_part()
    {
        // Real shape (observed 2026-07-30): message.id + message.usage repeated on every JSONL line
        // of the same API call; the extra usage sub-objects (cache_creation, server_tool_use) are ignored.
        const string line = """{"type":"assistant","uuid":"u5","timestamp":"2026-07-30T10:00:05.000Z","message":{"id":"msg_011abc","role":"assistant","stop_reason":"end_turn","usage":{"input_tokens":2,"cache_creation_input_tokens":43688,"cache_read_input_tokens":12000,"output_tokens":372,"service_tier":"standard","cache_creation":{"ephemeral_1h_input_tokens":43688,"ephemeral_5m_input_tokens":0}},"content":[{"type":"thinking","thinking":"hm"},{"type":"text","text":"Done."}]}}""";

        var parts = TranscriptNormalizer.Normalize(line);

        parts.Count.ShouldBe(3); // thinking + text + turn end
        foreach (var part in parts)
        {
            part.ApiCallId.ShouldBe("msg_011abc");
            part.InputTokens.ShouldBe(2);
            part.OutputTokens.ShouldBe(372);
            part.CacheReadTokens.ShouldBe(12000);
            part.CacheCreationTokens.ShouldBe(43688);
        }
    }

    [Test]
    public void Assistant_without_usage_yields_null_token_fields()
    {
        const string line = """{"type":"assistant","uuid":"u6","message":{"role":"assistant","stop_reason":"end_turn","content":[{"type":"text","text":"ok"}]}}""";

        var parts = TranscriptNormalizer.Normalize(line);

        parts.Count.ShouldBe(2);
        parts[0].ApiCallId.ShouldBeNull();
        parts[0].InputTokens.ShouldBeNull();
        parts[0].OutputTokens.ShouldBeNull();
        parts[0].CacheReadTokens.ShouldBeNull();
        parts[0].CacheCreationTokens.ShouldBeNull();
    }

    [Test]
    public void User_records_never_carry_usage()
    {
        const string line = """{"type":"user","message":{"role":"user","content":"run the app"}}""";

        var part = TranscriptNormalizer.Normalize(line).ShouldHaveSingleItem();
        part.ApiCallId.ShouldBeNull();
        part.OutputTokens.ShouldBeNull();
    }

    [Test]
    public void Meta_user_records_are_skipped()
    {
        const string line = """{"type":"user","isMeta":true,"message":{"role":"user","content":[{"type":"text","text":"<system>"}]}}""";

        TranscriptNormalizer.Normalize(line).ShouldBeEmpty();
    }

    [Test]
    public void Invalid_blank_and_metadata_only_lines_yield_nothing()
    {
        TranscriptNormalizer.Normalize("not json").ShouldBeEmpty();
        TranscriptNormalizer.Normalize("").ShouldBeEmpty();
        TranscriptNormalizer.Normalize("""{"type":"file-history-snapshot"}""").ShouldBeEmpty();
        TranscriptNormalizer.Normalize("""{"type":"last-prompt","lastPrompt":"x"}""").ShouldBeEmpty();
    }
}
