using System.Text;
using Antiphon.Server.Application.Services;
using Shouldly;
using TUnit.Core;

namespace Antiphon.Tests.Application;

[Category("Unit")]
public sealed class OrchestratorInstructionsRendererTests
{
    [Test]
    public void Render_is_deterministic_and_version_is_the_body_hash()
    {
        var snapshot = Sample();
        var first = OrchestratorInstructionsRenderer.Render(snapshot);
        var second = OrchestratorInstructionsRenderer.Render(snapshot);
        second.ShouldBe(first);
        var version = OrchestratorInstructionsRenderer.VersionOf(first);
        version.ShouldBe(InstructionFileStamps.HashOf(InstructionFileStamps.Normalise(first)));
        version.Length.ShouldBe(8);
        first.ShouldNotContain("[orchestrator-instructions v");
    }

    [Test]
    public void Header_declares_generated_and_names_the_route()
    {
        var body = OrchestratorInstructionsRenderer.Render(Sample());
        body.ShouldContain("Generated by Antiphon from live settings");
        body.ShouldContain("Do not edit this");
        body.ShouldContain("GET /api/orchestrator-instructions");
    }

    [Test]
    public void Sections_render_caps_runners_defaults_holds_pins_levels_and_standing_lines()
    {
        var body = OrchestratorInstructionsRenderer.Render(Sample());
        body.ShouldContain("## 1. Pipeline caps");
        body.ShouldContain("## 2. Hosts and runners");
        body.ShouldContain("## 3. Runner defaults");
        body.ShouldContain("## 4. Held models");
        body.ShouldContain("## 5. Routing pins");
        body.ShouldContain("## 6. Model levels");
        body.ShouldContain("## 7. Operator standing instructions");
        body.ShouldContain("recommended in-flight");
        body.ShouldContain("| Code |");
        body.ShouldContain("-IgnoreConcurrencyLimit");
        body.ShouldContain("GET /api/agent-tasks/pipeline");
        body.ShouldContain("desktop:");
        body.ShouldContain("server2:");
        body.ShouldContain("global server2");
        body.ShouldContain("operator moved the default");
        body.ShouldContain("ClaudeCode/fable");
        body.ShouldContain("stage-wide Code");
        body.ShouldContain("Antiphon CARD-0822 Code");
        body.ShouldContain("fable");
        body.ShouldContain("opus");
        body.ShouldContain("sonnet");
        body.ShouldContain("haiku");
        body.ShouldContain("prefer the live file");
        body.ShouldContain("CARD-0262");
        body.ShouldContain("Tier names are never -Kind values.");
        body.ShouldNotContain("occupied");
    }

    [Test]
    public void Occupancy_and_timestamps_are_not_rendered()
    {
        var left = Sample();
        var right = left with
        {
            Runners =
            [
                left.Runners[0] with { Occupied = 9, ObservedAt = "2099-01-01T00:00:00Z" },
                left.Runners[1] with { Occupied = 0, ObservedAt = "1999-01-01T00:00:00Z" },
            ],
        };
        OrchestratorInstructionsRenderer.Render(right)
            .ShouldBe(OrchestratorInstructionsRenderer.Render(left));
    }

    [Test]
    public void Oversized_snapshot_truncates_in_priority_order_under_the_byte_cap()
    {
        var pins = Enumerable.Range(0, 200).Select(i => new PinInstructionRow(
            StageWide: false,
            BoardName: "Antiphon",
            CardIdentifier: "CARD-" + i.ToString("0000"),
            Role: "Code",
            Candidates: ["claude"],
            ForbiddenAliases: [],
            Strength: "prefer",
            Provenance: "human",
            NotBefore: null,
            NotAfter: null,
            Reason: new string('p', 80),
            CreatedAt: DateTimeOffset.Parse("2026-01-01T00:00:00Z").AddMinutes(i))).ToList();
        var holds = Enumerable.Range(0, 60).Select(i => new HoldInstructionRow(
            "ClaudeCode",
            "alias-" + i,
            "Manual",
            "2099-01-01T00:00:00Z",
            new string('h', 180),
            DateTimeOffset.Parse("2026-01-01T00:00:00Z").AddMinutes(i))).ToList();
        var runners = Enumerable.Range(0, 50).Select(i => new RunnerInstructionRow(
            "runner-" + i,
            "linux",
            true,
            4,
            4,
            "configured",
            false,
            false,
            [new string('f', 280)])).ToList();
        var standing = Enumerable.Range(0, 10).Select(i => new string('s', 280) + i).ToList();
        var snapshot = Sample() with
        {
            Pins = pins,
            Holds = holds,
            Runners = runners,
            StandingLines = standing,
        };

        var body = OrchestratorInstructionsRenderer.Render(snapshot);
        Encoding.UTF8.GetByteCount(body).ShouldBeLessThanOrEqualTo(16_384);
        body.ShouldContain("## 1. Pipeline caps");
        body.ShouldContain("| Code |");
        body.ShouldContain("-IgnoreConcurrencyLimit");
        var pinsAt = body.IndexOf("more: GET /api/routing-pins", StringComparison.Ordinal);
        var holdsAt = body.IndexOf("more: GET /api/model-availability", StringComparison.Ordinal);
        var standingAt = body.IndexOf("more: GET /api/orchestrator-instructions", StringComparison.Ordinal);
        var featuresAt = body.IndexOf("more: GET /api/session-runners", StringComparison.Ordinal);
        pinsAt.ShouldBeGreaterThanOrEqualTo(0);
        holdsAt.ShouldBeGreaterThan(pinsAt);
        standingAt.ShouldBeGreaterThan(holdsAt);
        featuresAt.ShouldBeGreaterThan(standingAt);
    }

    [Test]
    [Arguments("{{key:x}}")]
    [Arguments("ANTHROPIC_API_KEY=abc")]
    [Arguments("X-Antiphon-Operator-Token: abc")]
    public void Secret_shaped_content_refuses_the_render(string standingLine)
    {
        var snapshot = Sample() with { StandingLines = [standingLine] };
        Should.Throw<OrchestratorInstructionsRefusedException>(
            () => OrchestratorInstructionsRenderer.Render(snapshot));
    }

    private static OrchestratorInstructionsSnapshot Sample() => new(
        Caps: new PipelineCapsSection(
            EffectiveMaxConcurrentTasks: 2,
            MaxConcurrentSource: "configured",
            MaxOpenTasks: 6,
            DefaultWorkerWorkspace: "Worktree",
            MinOrchestratorLevel: "High",
            Roles:
            [
                new RoleInstructionRow("Code", 2, "Frontier", null, "ClaudeCode"),
                new RoleInstructionRow("Review", 2, "Frontier", null, null),
            ]),
        Runners:
        [
            new RunnerInstructionRow("desktop", "windows", true, 2, 2, "configured", false, false, ["pty"], Occupied: 1, ObservedAt: "2026-10-10T00:00:00Z"),
            new RunnerInstructionRow("server2", "linux", true, 10, 10, "declared", false, false, ["pty"], Occupied: 3, ObservedAt: "2026-10-10T00:00:00Z"),
        ],
        Defaults: new RunnerDefaultsSection(2, "Human", "server2", [new KindDefaultInstruction("ClaudeCode", "server2")], "operator moved the default"),
        Holds: [new HoldInstructionRow("ClaudeCode", "fable", "Manual", "2099-01-01T00:00:00Z", "session limit")],
        Pins:
        [
            new PinInstructionRow(true, null, null, "Code", ["opus"], ["fable"], "require", "human", null, null, "stage pin", DateTimeOffset.Parse("2026-10-01T00:00:00Z")),
            new PinInstructionRow(false, "Antiphon", "CARD-0822", "Code", ["opus"], [], "prefer", "human", null, null, "card pin", DateTimeOffset.Parse("2026-10-02T00:00:00Z")),
        ],
        Levels:
        [
            new LevelInstructionRow("ClaudeCode", "Frontier", "fable"),
            new LevelInstructionRow("ClaudeCode", "High", "opus"),
            new LevelInstructionRow("ClaudeCode", "Medium", "sonnet"),
            new LevelInstructionRow("ClaudeCode", "Low", "haiku"),
            new LevelInstructionRow("Codex", "Frontier", "gpt-6-astra"),
            new LevelInstructionRow("Grok", "High", "grok-4.7"),
        ],
        StandingLines: ["prefer the live file"]);
}
