using System.Text;
using Antiphon.Server.Application.Settings;

namespace Antiphon.Server.Application.Services;

/// <summary>
/// Pure Markdown for one <see cref="OrchestratorInstructionsSnapshot"/>. The stamp line is not
/// part of this text: the version is the hash of this body, so a revision bump does not change it.
/// </summary>
public static class OrchestratorInstructionsRenderer
{
    public const string PinsRoute = "GET /api/routing-pins";
    public const string HoldsRoute = "GET /api/model-availability";
    public const string RunnersRoute = "GET /api/session-runners";
    public const string FileRoute = "GET /api/orchestrator-instructions";
    public const string PipelineRoute = "GET /api/agent-tasks/pipeline";

    private static readonly string[] SecretTokens =
    [
        "{{key:",
        "ANTHROPIC_API_KEY",
        "ANTHROPIC_AUTH_TOKEN",
        "CLAUDE_CODE_OAUTH_TOKEN",
        "OPENAI_API_KEY",
        "XAI_API_KEY",
        "GROK_CODE_XAI_API_KEY",
        "X-Antiphon-Operator-Token",
        "SharedSecret",
    ];

    public static string VersionOf(string body) =>
        InstructionFileStamps.HashOf(InstructionFileStamps.Normalise(body));

    public static string Render(OrchestratorInstructionsSnapshot snapshot, int? maxBytes = null)
    {
        ArgumentNullException.ThrowIfNull(snapshot);
        var cap = maxBytes ?? OrchestratorInstructionsSettings.DefaultMaxBytes;
        var text = Fit(snapshot, cap);
        RefuseSecrets(text);
        return text;
    }

    private static string Fit(OrchestratorInstructionsSnapshot snapshot, int cap)
    {
        var cardPerBoard = int.MaxValue;
        var holdCount = int.MaxValue;
        var standingCount = snapshot.StandingLines.Count;
        var features = true;

        var text = Compose(snapshot, cardPerBoard, holdCount, standingCount, features);
        if (Bytes(text) <= cap)
            return text;

        cardPerBoard = 20;
        text = Compose(snapshot, cardPerBoard, holdCount, standingCount, features);
        while (Bytes(text) > cap && cardPerBoard > 0)
        {
            cardPerBoard--;
            text = Compose(snapshot, cardPerBoard, holdCount, standingCount, features);
        }

        if (Bytes(text) <= cap)
            return text;

        holdCount = Math.Min(20, snapshot.Holds.Count);
        text = Compose(snapshot, cardPerBoard, holdCount, standingCount, features);
        while (Bytes(text) > cap && holdCount > 0)
        {
            holdCount--;
            text = Compose(snapshot, cardPerBoard, holdCount, standingCount, features);
        }

        if (Bytes(text) <= cap)
            return text;

        while (Bytes(text) > cap && standingCount > 0)
        {
            standingCount--;
            text = Compose(snapshot, cardPerBoard, holdCount, standingCount, features);
        }

        if (Bytes(text) <= cap)
            return text;

        features = false;
        return Compose(snapshot, cardPerBoard, holdCount, standingCount, features);
    }

    private static string Compose(
        OrchestratorInstructionsSnapshot snapshot,
        int cardPerBoard,
        int holdCount,
        int standingCount,
        bool features)
    {
        var pins = SelectPins(snapshot.Pins, cardPerBoard);
        var holds = SelectHolds(snapshot.Holds, holdCount);
        var standing = snapshot.StandingLines.Take(Math.Max(0, standingCount)).ToList();
        var cardTotal = snapshot.Pins.Count(p => !p.StageWide);
        var cardKept = pins.Count(p => !p.StageWide);
        var pinsOmitted = cardTotal - cardKept;
        var holdsOmitted = snapshot.Holds.Count - holds.Count;
        var standingOmitted = snapshot.StandingLines.Count - standing.Count;
        var featureRunners = snapshot.Runners.Count(r => r.Features.Count > 0);

        var builder = new StringBuilder();
        builder.AppendLine("Generated by Antiphon from live settings and overwritten on every covered change. Do not edit this");
        builder.AppendLine("file; change the setting each section names. Live copy: " + FileRoute + ".");
        builder.AppendLine();

        builder.AppendLine("## 1. Pipeline caps");
        builder.AppendLine(
            $"MaxConcurrentTasks: {snapshot.Caps.EffectiveMaxConcurrentTasks} (effective local budget, source {snapshot.Caps.MaxConcurrentSource}).");
        builder.AppendLine(
            $"MaxOpenTasks: {snapshot.Caps.MaxOpenTasks} (per project scope; the effective absolute cap).");
        builder.AppendLine($"DefaultWorkerWorkspace: {snapshot.Caps.DefaultWorkerWorkspace}.");
        builder.AppendLine($"MinOrchestratorLevel: {snapshot.Caps.MinOrchestratorLevel}.");
        builder.AppendLine();
        builder.AppendLine("| Role | recommended in-flight | Level | EscalateTo | Kind |");
        builder.AppendLine("| --- | --- | --- | --- | --- |");
        foreach (var role in snapshot.Caps.Roles)
        {
            builder.AppendLine(
                $"| {role.Role} | {FormatInFlight(role.RecommendedInFlight)} | {role.Level} | {role.EscalateTo ?? ""} | {role.Kind ?? ""} |");
        }

        builder.AppendLine();
        builder.AppendLine(
            "Create refuses at the recommended in-flight number unless -IgnoreConcurrencyLimit. Live counts: "
            + PipelineRoute + ".");
        builder.AppendLine();

        builder.AppendLine("## 2. Hosts and runners");
        builder.AppendLine("Owner: " + RunnersRoute + ".");
        if (snapshot.Runners.Count == 0)
            builder.AppendLine("none");
        foreach (var runner in snapshot.Runners)
            builder.AppendLine(FormatRunner(runner, features));
        builder.AppendLine();

        builder.AppendLine("## 3. Runner defaults");
        builder.AppendLine(
            $"revision {snapshot.Defaults.Revision}; provenance {snapshot.Defaults.Provenance ?? "none"}; "
            + $"global {snapshot.Defaults.GlobalRunnerId ?? "none"}; reason {snapshot.Defaults.LastReason ?? "none"}.");
        foreach (var kind in snapshot.Defaults.KindDefaults)
            builder.AppendLine($"- {kind.Kind}: {kind.RunnerId ?? "none"}");
        builder.AppendLine();

        builder.AppendLine("## 4. Held models");
        builder.AppendLine("Owner: " + HoldsRoute + ".");
        if (holds.Count == 0)
            builder.AppendLine("none");
        foreach (var hold in holds)
        {
            builder.AppendLine(
                $"- {hold.Kind}/{hold.Alias} {hold.Source} until {hold.Until ?? "none"}; {hold.Reason ?? ""}");
        }

        builder.AppendLine();

        builder.AppendLine("## 5. Routing pins");
        builder.AppendLine("Owner: " + PinsRoute + ".");
        if (pins.Count == 0)
            builder.AppendLine("none");
        foreach (var pin in pins)
            builder.AppendLine(FormatPin(pin));
        builder.AppendLine();

        builder.AppendLine("## 6. Model levels");
        foreach (var level in snapshot.Levels)
            builder.AppendLine($"- {level.Kind} {level.Level}: {level.Alias}");
        builder.AppendLine("Tier names are never -Kind values.");
        builder.AppendLine();

        builder.AppendLine("## 7. Operator standing instructions");
        builder.AppendLine("Owner: " + FileRoute + ".");
        if (standing.Count == 0)
            builder.AppendLine("none");
        foreach (var line in standing)
            builder.AppendLine("- " + line);
        builder.AppendLine(
            "Per-agent pinned instructions (CARD-0262) are projected into the agent's own workspace and are not repeated here.");

        // Cut notices follow the truncation priority, not the section order, so a reader sees
        // what was dropped first: card pins, holds, standing lines, then the features column.
        if (pinsOmitted > 0)
            builder.AppendLine($"… {pinsOmitted} more: {PinsRoute}");
        if (holdsOmitted > 0)
            builder.AppendLine($"… {holdsOmitted} more: {HoldsRoute}");
        if (standingOmitted > 0)
            builder.AppendLine($"… {standingOmitted} more: {FileRoute}");
        if (!features && featureRunners > 0)
            builder.AppendLine($"… {featureRunners} more: {RunnersRoute}");

        return builder.ToString().TrimEnd();
    }

    private static string FormatRunner(RunnerInstructionRow runner, bool features)
    {
        var flags = new List<string>();
        if (runner.Draining)
            flags.Add("draining");
        if (runner.Retired)
            flags.Add("retired");
        var flagText = flags.Count == 0 ? "" : "; " + string.Join("; ", flags);
        var featureText = features
            ? "; features " + (runner.Features.Count == 0 ? "none" : string.Join(", ", runner.Features))
            : "";
        return $"- {runner.RunnerId}: platform {runner.Platform ?? "unknown"}; dispatch-eligible "
            + $"{(runner.DispatchEligible ? "yes" : "no")}; declared capacity {FormatOptional(runner.DeclaredCapacity)}; "
            + $"effective budget {FormatOptional(runner.EffectiveBudget)} ({runner.BudgetSource ?? "none"})"
            + flagText + featureText;
    }

    private static string FormatPin(PinInstructionRow pin)
    {
        var who = pin.StageWide
            ? $"stage-wide {pin.Role}"
            : $"{pin.BoardName ?? "board"} {pin.CardIdentifier ?? "card"} {pin.Role}";
        var forbidden = pin.ForbiddenAliases.Count == 0
            ? ""
            : "; forbidden " + string.Join(", ", pin.ForbiddenAliases);
        return $"- {who}: candidates {string.Join(", ", pin.Candidates)}; strength {pin.Strength ?? "none"}; "
            + $"provenance {pin.Provenance ?? "none"}; not-before {pin.NotBefore ?? "none"}; "
            + $"not-after {pin.NotAfter ?? "none"}{forbidden}; {pin.Reason ?? ""}";
    }

    private static List<PinInstructionRow> SelectPins(IReadOnlyList<PinInstructionRow> pins, int perBoard)
    {
        var stage = pins.Where(p => p.StageWide).ToList();
        var cards = new List<PinInstructionRow>();
        foreach (var group in pins.Where(p => !p.StageWide).GroupBy(p => p.BoardName ?? "", StringComparer.Ordinal))
        {
            var ordered = group
                .OrderByDescending(p => p.CreatedAt)
                .ThenBy(p => p.CardIdentifier, StringComparer.Ordinal)
                .ToList();
            var take = perBoard == int.MaxValue ? ordered.Count : Math.Min(perBoard, ordered.Count);
            cards.AddRange(ordered.Take(take));
        }

        return stage
            .Concat(cards.OrderBy(p => p.BoardName, StringComparer.Ordinal).ThenByDescending(p => p.CreatedAt))
            .ToList();
    }

    private static List<HoldInstructionRow> SelectHolds(IReadOnlyList<HoldInstructionRow> holds, int limit)
    {
        if (limit >= holds.Count)
            return holds.ToList();
        return holds
            .OrderByDescending(h => h.ObservedAt ?? DateTimeOffset.MinValue)
            .Take(Math.Max(0, limit))
            .ToList();
    }

    private static string FormatInFlight(int? value) => value?.ToString() ?? "unbounded";

    private static string FormatOptional(int? value) => value?.ToString() ?? "none";

    private static int Bytes(string text) => Encoding.UTF8.GetByteCount(text);

    private static void RefuseSecrets(string text)
    {
        foreach (var token in SecretTokens)
        {
            if (text.Contains(token, StringComparison.Ordinal))
                throw new OrchestratorInstructionsRefusedException();
        }
    }
}
