using Antiphon.Server.Application.Interfaces;

namespace Antiphon.Server.Infrastructure.Agents;

/// <summary>
/// Default IStageExecutor implementation (AR6) that produces placeholder artifacts for testing.
/// </summary>
public class MockExecutor : IStageExecutor
{
    public Task<StageExecutionResult> ExecuteAsync(StageExecutionContext context, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        var outputContent = $"""
            # {context.StageName} Output

            This is a placeholder artifact generated by MockExecutor for testing.

            ## Execution Details
            - Workflow: {context.WorkflowId}
            - Stage: {context.StageId}
            - Executor: {context.ExecutorType}
            - Model: {context.ModelName ?? "N/A"}
            - Upstream artifacts: {context.UpstreamArtifacts.Count}
            """;

        var artifactPath = $"_antiphon/artifacts/{context.WorkflowId}/{context.StageName}.md";

        var result = new StageExecutionResult(
            OutputContent: outputContent,
            ArtifactPaths: [artifactPath],
            SuggestedActions: null);

        return Task.FromResult(result);
    }
}
