<#
.SYNOPSIS
    CARD-0644 test fixture: a scratch bare origin, its main clone and a linked
    worktree carrying copies of the real AppHost entry points, plus an inert
    seam file that records every side effect instead of performing it.

    Dot-sourced by scripts/test-card0644-local-deploy.ps1 and
    scripts/test-apphost-main-worktree-guard.ps1. Never touches the real
    checkout, live 172xx ports, processes, Docker or scheduled tasks: every
    entry point runs from the scratch repositories with
    ANTIPHON_APPHOST_TEST_SEAMS pointing at the seam file below.
    ASCII-only for pwsh 7 and Windows PowerShell 5.1.
#>

$script:C644ScriptsDir = Split-Path -Parent $PSScriptRoot

function Invoke-C644Git {
    # Deliberately not an advanced function: git flags such as -qm land in $args.
    param([string]$Root)
    $GitArgs = @($args)
    $out = @(& git -C $Root @GitArgs 2>&1 | ForEach-Object { $_.ToString() })
    if ($LASTEXITCODE -ne 0) { throw ('git {0} failed in {1}: {2}' -f ($GitArgs -join ' '), $Root, ($out -join ' ')) }
    return $out
}

function Get-C644Head {
    param([string]$Root)
    return ((Invoke-C644Git $Root rev-parse HEAD) | Select-Object -First 1).Trim().ToLowerInvariant()
}

function New-C644Commit {
    param([string]$Root, [string]$Message)
    Add-Content -LiteralPath (Join-Path $Root 'README.md') -Value $Message -Encoding ASCII
    Invoke-C644Git $Root add README.md | Out-Null
    Invoke-C644Git $Root commit -qm $Message | Out-Null
    return Get-C644Head $Root
}

function Write-C644SeamFile {
    param([string]$Path)
    $seams = @(
        '# CARD-0644 inert AppHost seams (generated by scripts/lib/card0644-apphost-fixture.ps1)'
        '$script:C644Harness = Split-Path $PSCommandPath -Parent'
        '$script:C644Trace = Join-Path $script:C644Harness ''trace.jsonl'''
        '$script:C644Cfg = Get-Content -LiteralPath (Join-Path $script:C644Harness ''cfg.json'') -Raw | ConvertFrom-Json'
        '$script:C644HeadCalls = 0'
        '$script:C644VersionCalls = 0'
        'function Write-C644Trace([string]$Kind, $Extra) {'
        '  $row = @{ kind = $Kind; proc = $PID; child = [bool]$env:C644_CHILD; at = [datetime]::UtcNow.ToString(''o'') }'
        '  if ($Extra) { foreach ($k in $Extra.Keys) { $row[$k] = $Extra[$k] } }'
        '  Add-Content -LiteralPath $script:C644Trace -Value ($row | ConvertTo-Json -Compress) -Encoding ASCII'
        '}'
        'function Get-AppHostPortOwners { param([int]$Port) Write-C644Trace ''port'' @{ port = $Port }; return @() }'
        'function Stop-AppHostProcessId { param([int]$ProcessId) Write-C644Trace ''stop-id'' @{ pid = $ProcessId } }'
        'function Stop-AppHostProcessTree { param([int]$ProcessId) Write-C644Trace ''stop-tree'' @{ pid = $ProcessId } }'
        'function Get-AppHostStrayProcesses { Write-C644Trace ''stray'' @{}; return @() }'
        'function Stop-AppHostLaunchChild { param($Process) Write-C644Trace ''child-stop'' @{} }'
        'function Start-AppHostDevLaunch { param([string[]]$ArgumentList)'
        '  Write-C644Trace ''launch'' @{ args = ($ArgumentList -join '' '') }'
        '  $n = @(Get-Content -LiteralPath $script:C644Trace | Where-Object { $_ -match ''"kind":"launch"'' }).Count'
        '  $prev = $env:C644_CHILD'
        '  $env:C644_CHILD = ''1'''
        '  try { $out = @(& pwsh -NoProfile @ArgumentList 2>&1 | ForEach-Object { $_.ToString() }); $code = $LASTEXITCODE }'
        '  finally { $env:C644_CHILD = $prev }'
        '  Set-Content -LiteralPath (Join-Path $script:C644Harness (''child-'' + $n + ''.log'')) -Value $out -Encoding ASCII'
        '  Write-C644Trace ''child-exit'' @{ code = $code }'
        '  return [pscustomobject]@{ Id = 99999; HasExited = $true }'
        '}'
        'function Invoke-AppHostHealthProbe { param([int]$TimeoutSec = 5)'
        '  Write-C644Trace ''health'' @{}'
        '  return [pscustomobject]@{ StatusCode = 200; Body = ''Healthy''; Error = $null }'
        '}'
        'function Invoke-AppHostVersionProbe { param([int]$TimeoutSec = 5)'
        '  $script:C644VersionCalls++'
        '  Write-C644Trace ''version'' @{}'
        '  $sha = [string]$script:C644Cfg.versionSha'
        '  $body = (''{{"version":"{0}","informationalVersion":"{0}","capabilities":["land-v2"]}}'' -f $sha)'
        '  return [pscustomobject]@{ StatusCode = 200; Body = $body; Error = $null }'
        '}'
        'function Wait-AppHostPollInterval { param([int]$Seconds = 3) Write-C644Trace ''wait'' @{} }'
        'function Get-AppHostSourceHead { param([string]$SourceRoot)'
        '  $script:C644HeadCalls++'
        '  if (-not $env:C644_CHILD -and $script:C644Cfg.commitOnHeadCall -and ($script:C644HeadCalls -eq [int]$script:C644Cfg.commitOnHeadCall)) {'
        '    Add-Content -LiteralPath (Join-Path $SourceRoot ''README.md'') ''moved'' -Encoding ASCII'
        '    & git -C $SourceRoot add README.md | Out-Null'
        '    & git -C $SourceRoot commit -qm ''c644 moved head'' | Out-Null'
        '    Write-C644Trace ''head-moved'' @{}'
        '  }'
        '  try {'
        '    $text = ((& git -C $SourceRoot rev-parse HEAD 2>$null) | Select-Object -First 1).ToString().Trim()'
        '    if ($text -match ''^[0-9a-fA-F]{40}$'' -or $text -match ''^[0-9a-fA-F]{64}$'') { return $text.ToLowerInvariant() }'
        '    return $null'
        '  } catch { return $null }'
        '}'
        'function Show-DcpTimeoutVerdict { param($LogPath,$Evidence,[bool]$PodmanNoise=$false,$LaunchLock,$RestartLock,$WatchdogLog,[int]$DockerTimeoutSec=10) Write-C644Trace ''dcp'' @{} }'
        'function Get-DockerVerdict { param([int]$TimeoutSec=10) return [pscustomobject]@{ Healthy = $true; Summary = ''seamed''; Detail = @() } }'
        'function Get-RecordedMigrationIds { Write-C644Trace ''migrations'' @{}; return @($script:C644Cfg.migrations) }'
        'function Invoke-AppHostDevLaunchSeam { param([string]$Root, [string]$LaunchLock, $Bound)'
        '  $argText = @($Bound.Keys | Sort-Object | ForEach-Object { ''{0}={1}'' -f $_, $Bound[$_] }) -join '' '''
        '  Write-C644Trace ''dev-body'' @{ root = $Root; lockDir = (Split-Path -Parent $LaunchLock); lockHeld = (Test-Path -LiteralPath $LaunchLock); args = $argText }'
        '  Set-Content -LiteralPath (Join-Path (Split-Path -Parent $LaunchLock) ''apphost-dashboard-url.txt'') ''http://127.0.0.1:9/'' -Encoding ASCII'
        '}'
    )
    $seams | Set-Content -LiteralPath $Path -Encoding ASCII
}

function New-C644Fixture {
    <#
      Returns Base, Origin, Main, Linked, Harness, Seams, OriginSha. Main and
      Linked both start at OriginSha == refs/remotes/origin/master. The linked
      worktree is on its own branch so a commit there leaves main untouched.
    #>
    param($Config = @{})
    $base = Join-Path ([System.IO.Path]::GetTempPath()) ('c644-' + [guid]::NewGuid().ToString('N').Substring(0, 12))
    $origin = Join-Path $base 'origin.git'
    $main = Join-Path $base 'main'
    $linked = Join-Path $base 'linked'
    $harness = Join-Path $base 'harness'
    New-Item -ItemType Directory -Force $base, $harness | Out-Null
    & git init -q --bare $origin 2>&1 | Out-Null
    & git clone -q $origin $main 2>&1 | Out-Null
    Invoke-C644Git $main config user.email c644@example.test | Out-Null
    Invoke-C644Git $main config user.name c644 | Out-Null
    Invoke-C644Git $main config commit.gpgsign false | Out-Null
    Invoke-C644Git $main checkout -q -b master | Out-Null

    $scripts = Join-Path $main 'scripts'
    New-Item -ItemType Directory -Force $scripts, (Join-Path (Join-Path $main 'server') 'Migrations') | Out-Null
    foreach ($name in 'apphost-common.ps1', 'restart-apphost.ps1', 'deploy-local.ps1') {
        Copy-Item -LiteralPath (Join-Path $script:C644ScriptsDir $name) -Destination (Join-Path $scripts $name) -Force
    }
    Copy-Item -LiteralPath (Join-Path (Split-Path -Parent $script:C644ScriptsDir) 'dev-aspire.ps1') -Destination (Join-Path $main 'dev-aspire.ps1') -Force
    @('# inert CARD-0644', 'Write-Host "check-daemon-build inert"') |
        Set-Content -LiteralPath (Join-Path $scripts 'check-daemon-build.ps1') -Encoding ASCII
    @('# inert CARD-0644 verify-dev-stack', 'Set-Content -LiteralPath (Join-Path $PSScriptRoot ''verify-invoked.txt'') ''invoked'' -Encoding ASCII', 'exit 0') |
        Set-Content -LiteralPath (Join-Path $main 'verify-dev-stack.ps1') -Encoding ASCII
    '// c644 migration' | Set-Content -LiteralPath (Join-Path (Join-Path (Join-Path $main 'server') 'Migrations') '20260101000000_C644Init.cs') -Encoding ASCII
    'c644 seed' | Set-Content -LiteralPath (Join-Path $main 'README.md') -Encoding ASCII
    'logs/' | Set-Content -LiteralPath (Join-Path $main '.gitignore') -Encoding ASCII
    Invoke-C644Git $main add -A | Out-Null
    Invoke-C644Git $main commit -qm 'c644 fixture' | Out-Null
    Invoke-C644Git $main push -q origin master | Out-Null
    $originSha = Get-C644Head $main
    Invoke-C644Git $main worktree add -q -b feat/c644-linked $linked $originSha | Out-Null

    $cfg = @{ versionSha = $originSha; migrations = @('20260101000000_C644Init') }
    foreach ($k in $Config.Keys) { $cfg[$k] = $Config[$k] }
    ($cfg | ConvertTo-Json -Depth 5) | Set-Content -LiteralPath (Join-Path $harness 'cfg.json') -Encoding ASCII
    $seamPath = Join-Path $harness 'seams.ps1'
    Write-C644SeamFile -Path $seamPath

    return [pscustomobject]@{
        Base = $base; Origin = $origin; Main = $main; Linked = $linked
        Harness = $harness; Seams = $seamPath; OriginSha = $originSha
    }
}

function Set-C644Config {
    param($Fixture, $Config)
    $cfgPath = Join-Path $Fixture.Harness 'cfg.json'
    $cfg = @{}
    $current = Get-Content -LiteralPath $cfgPath -Raw | ConvertFrom-Json
    foreach ($p in $current.PSObject.Properties) { $cfg[$p.Name] = $p.Value }
    foreach ($k in $Config.Keys) { $cfg[$k] = $Config[$k] }
    ($cfg | ConvertTo-Json -Depth 5) | Set-Content -LiteralPath $cfgPath -Encoding ASCII
}

function Remove-C644Fixture {
    param($Fixture)
    if (-not $Fixture -or -not $Fixture.Base) { return }
    $tmp = [System.IO.Path]::GetFullPath([System.IO.Path]::GetTempPath())
    $full = [System.IO.Path]::GetFullPath($Fixture.Base)
    if ($full.StartsWith($tmp) -and (Split-Path -Leaf $full) -like 'c644-*' -and (Test-Path -LiteralPath $full)) {
        Remove-Item -LiteralPath $full -Recurse -Force -ErrorAction SilentlyContinue
    }
}

function Invoke-C644Entry {
    <#
      Runs one real entry point (restart | deploy | dev) rooted at $Root with the
      fixture's inert seams. Returns ExitCode, Text and the trace rows written.
    #>
    param($Fixture, [ValidateSet('restart', 'deploy', 'dev')][string]$Entry, [string]$Root, [string[]]$Arguments = @())
    $path = switch ($Entry) {
        'restart' { Join-Path (Join-Path $Root 'scripts') 'restart-apphost.ps1' }
        'deploy'  { Join-Path (Join-Path $Root 'scripts') 'deploy-local.ps1' }
        'dev'     { Join-Path $Root 'dev-aspire.ps1' }
    }
    $trace = Join-Path $Fixture.Harness 'trace.jsonl'
    if (Test-Path -LiteralPath $trace) { Remove-Item -LiteralPath $trace -Force }
    $prevSeams = $env:ANTIPHON_APPHOST_TEST_SEAMS
    $env:ANTIPHON_APPHOST_TEST_SEAMS = $Fixture.Seams
    $prevLocation = Get-Location
    try {
        Set-Location $Fixture.Base
        $output = @(& pwsh -NoProfile -File $path @Arguments 2>&1 | ForEach-Object { $_.ToString() })
        $code = $LASTEXITCODE
    } finally {
        Set-Location $prevLocation
        if ($null -eq $prevSeams) { Remove-Item Env:ANTIPHON_APPHOST_TEST_SEAMS -ErrorAction SilentlyContinue }
        else { $env:ANTIPHON_APPHOST_TEST_SEAMS = $prevSeams }
    }
    $rows = @()
    if (Test-Path -LiteralPath $trace) { $rows = @(Get-Content -LiteralPath $trace | ForEach-Object { $_ | ConvertFrom-Json }) }
    $childText = @(Get-ChildItem -LiteralPath $Fixture.Harness -Filter 'child-*.log' -ErrorAction SilentlyContinue |
        ForEach-Object { Get-Content -LiteralPath $_.FullName -Raw; Remove-Item -LiteralPath $_.FullName -Force }) -join "`n"
    return [pscustomobject]@{ ExitCode = $code; Text = ($output -join "`n"); Trace = $rows; ChildText = $childText }
}

function Get-C644Count {
    param($Result, [string]$Kind)
    return @($Result.Trace | Where-Object { $_.kind -eq $Kind }).Count
}

function Get-C644EffectCount {
    <# Any teardown, launch or deploy-side effect the seams recorded. #>
    param($Result)
    return @($Result.Trace | Where-Object { $_.kind -in @('port', 'stop-id', 'stop-tree', 'stray', 'launch', 'dev-body', 'migrations') }).Count
}

function Set-C644Lock {
    param([string]$Path, [int]$HolderPid)
    New-Item -ItemType Directory -Force (Split-Path -Parent $Path) | Out-Null
    ('{0} {1}' -f $HolderPid, [datetime]::UtcNow.ToString('o')) | Set-Content -LiteralPath $Path -Encoding ASCII -NoNewline
}

function Get-C644GitPath {
    <# The path as Git reports it (long form on Windows), so comparisons match the entry points. #>
    param([string]$Root)
    $top = ((Invoke-C644Git $Root rev-parse --show-toplevel) | Select-Object -First 1).Trim()
    return [System.IO.Path]::GetFullPath($top.Replace('/', [System.IO.Path]::DirectorySeparatorChar))
}

function Test-C644SamePath {
    param([string]$Left, [string]$Right)
    if ([string]::IsNullOrWhiteSpace($Left) -or [string]::IsNullOrWhiteSpace($Right)) { return $false }
    $sep = [System.IO.Path]::DirectorySeparatorChar
    $a = [System.IO.Path]::GetFullPath($Left.Replace('/', $sep).Replace('\', $sep)).TrimEnd($sep)
    $b = [System.IO.Path]::GetFullPath($Right.Replace('/', $sep).Replace('\', $sep)).TrimEnd($sep)
    return [string]::Equals($a, $b, [System.StringComparison]::OrdinalIgnoreCase)
}
