// <auto-generated />
using System;
using Antiphon.Server.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Antiphon.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317005025_AddAuditAndCostLedger")]
    partial class AddAuditAndCostLedger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("FullContent")
                        .HasColumnType("jsonb");

                    b.Property<string>("GitTagName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ModelName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("StageExecutionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("TokensIn")
                        .HasColumnType("bigint");

                    b.Property<long>("TokensOut")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AuditRecords_CreatedAt");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_AuditRecords_EventType");

                    b.HasIndex("StageExecutionId");

                    b.HasIndex("StageId")
                        .HasDatabaseName("IX_AuditRecords_StageId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("IX_AuditRecords_WorkflowId");

                    b.ToTable("AuditRecords", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.CostLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuditRecordId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("StageExecutionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid");

                    b.Property<long>("TokensIn")
                        .HasColumnType("bigint");

                    b.Property<long>("TokensOut")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuditRecordId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_CostLedgerEntries_CreatedAt");

                    b.HasIndex("StageExecutionId");

                    b.HasIndex("StageId")
                        .HasDatabaseName("IX_CostLedgerEntries_StageId");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("IX_CostLedgerEntries_WorkflowId");

                    b.ToTable("CostLedgerEntries", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.GateDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DecidedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Feedback")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DecidedBy");

                    b.HasIndex("StageId")
                        .HasDatabaseName("IX_GateDecisions_StageId");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("IX_GateDecisions_WorkflowId");

                    b.ToTable("GateDecisions", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.LlmProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ProviderType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LlmProviders", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.ModelRouting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("StageName")
                        .IsUnique();

                    b.ToTable("ModelRoutings", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConstitutionPath")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("project-context.md");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("GitHubIntegrationEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("GitRepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Stage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExecutorType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("GateRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StageOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("IX_Stages_WorkflowId");

                    b.HasIndex("WorkflowId", "StageOrder")
                        .IsUnique()
                        .HasDatabaseName("IX_Stages_WorkflowId_StageOrder");

                    b.ToTable("Stages", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.StageExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<decimal>("EstimatedCostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("GitTagName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TokensIn")
                        .HasColumnType("bigint");

                    b.Property<long>("TokensOut")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StageId")
                        .HasDatabaseName("IX_StageExecutions_StageId");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("IX_StageExecutions_WorkflowId");

                    b.HasIndex("StageId", "Version")
                        .IsUnique()
                        .HasDatabaseName("IX_StageExecutions_StageId_Version");

                    b.ToTable("StageExecutions", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@antiphon.local",
                            IsAdmin = true,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentStageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("GitBranchName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("InitialContext")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurrentStageId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_Workflows_ProjectId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Workflows_Status");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("IX_Workflows_TemplateId");

                    b.ToTable("Workflows", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.WorkflowTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YamlDefinition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WorkflowTemplates", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.AuditRecord", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.StageExecution", "StageExecution")
                        .WithMany()
                        .HasForeignKey("StageExecutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Antiphon.Server.Domain.Entities.Stage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Antiphon.Server.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Antiphon.Server.Domain.Entities.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Stage");

                    b.Navigation("StageExecution");

                    b.Navigation("User");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.CostLedgerEntry", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.AuditRecord", "AuditRecord")
                        .WithMany()
                        .HasForeignKey("AuditRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Antiphon.Server.Domain.Entities.StageExecution", "StageExecution")
                        .WithMany()
                        .HasForeignKey("StageExecutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Antiphon.Server.Domain.Entities.Stage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Antiphon.Server.Domain.Entities.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditRecord");

                    b.Navigation("Stage");

                    b.Navigation("StageExecution");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.GateDecision", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.User", "DecidedByUser")
                        .WithMany()
                        .HasForeignKey("DecidedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Antiphon.Server.Domain.Entities.Stage", "Stage")
                        .WithMany("GateDecisions")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Antiphon.Server.Domain.Entities.Workflow", "Workflow")
                        .WithMany("GateDecisions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DecidedByUser");

                    b.Navigation("Stage");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.ModelRouting", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.LlmProvider", "Provider")
                        .WithMany("ModelRoutings")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Stage", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.Workflow", "Workflow")
                        .WithMany("Stages")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.StageExecution", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.Stage", "Stage")
                        .WithMany("StageExecutions")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Antiphon.Server.Domain.Entities.Workflow", "Workflow")
                        .WithMany("StageExecutions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Stage");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Workflow", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.Stage", "CurrentStage")
                        .WithMany()
                        .HasForeignKey("CurrentStageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Antiphon.Server.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Antiphon.Server.Domain.Entities.WorkflowTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentStage");

                    b.Navigation("Project");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.LlmProvider", b =>
                {
                    b.Navigation("ModelRoutings");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Stage", b =>
                {
                    b.Navigation("GateDecisions");

                    b.Navigation("StageExecutions");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Workflow", b =>
                {
                    b.Navigation("GateDecisions");

                    b.Navigation("StageExecutions");

                    b.Navigation("Stages");
                });
#pragma warning restore 612, 618
        }
    }
}
