// <auto-generated />
using System;
using Antiphon.Server.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Antiphon.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AlwaysOn")
                        .HasColumnType("boolean");

                    b.Property<int>("AssignmentPolicy")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentCardId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefaultWorkflowTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PersistentSessionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("RemoteControlEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SystemPromptAppend")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkingDirectory")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("BoardId")
                        .HasDatabaseName("IX_Agents_BoardId");

                    b.HasIndex("CurrentCardId");

                    b.HasIndex("DefaultWorkflowTemplateId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Agents_Slug");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Agents_Status");

                    b.ToTable("Agents", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.AgentIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "CreatedAt")
                        .HasDatabaseName("IX_AgentIncidents_AgentId_CreatedAt");

                    b.ToTable("AgentIncidents", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.AgentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgentKind")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CardId")
                        .HasColumnType("uuid");

                    b.Property<int>("Cols")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cwd")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DefinitionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rows")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WorktreeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .HasDatabaseName("IX_AgentSessions_CardId");

                    b.HasIndex("WorktreeId")
                        .HasDatabaseName("IX_AgentSessions_WorktreeId");

                    b.HasIndex("CardId", "Status")
                        .HasDatabaseName("IX_AgentSessions_CardId_Status");

                    b.ToTable("AgentSessions", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.AgentSupervisionState", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastEscalationTier")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastHealthyAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextRestartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Suspended")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AgentId");

                    b.ToTable("AgentSupervisionStates", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Detail")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("RoutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SuppressedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Alerts_CreatedAt");

                    b.HasIndex("DedupKey", "CreatedAt")
                        .HasDatabaseName("IX_Alerts_DedupKey_CreatedAt");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.ArtifactSectionReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SectionPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("StageExecutionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StageExecutionId")
                        .HasDatabaseName("IX_ArtifactSectionReviews_StageExecutionId");

                    b.HasIndex("StageExecutionId", "SectionPath")
                        .IsUnique()
                        .HasDatabaseName("IX_ArtifactSectionReviews_StageExecutionId_SectionPath");

                    b.ToTable("ArtifactSectionReviews", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("FullContent")
                        .HasColumnType("jsonb");

                    b.Property<string>("GitTagName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ModelName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("StageExecutionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("TokensIn")
                        .HasColumnType("bigint");

                    b.Property<long>("TokensOut")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AuditRecords_CreatedAt");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_AuditRecords_EventType");

                    b.HasIndex("StageExecutionId");

                    b.HasIndex("StageId")
                        .HasDatabaseName("IX_AuditRecords_StageId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("IX_AuditRecords_WorkflowId");

                    b.ToTable("AuditRecords", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("MaxConcurrentSessions")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("TrackerKind")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_Boards_ProjectId");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Boards_ProjectId_Name");

                    b.ToTable("Boards", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.BoardColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<int>("CardStatus")
                        .HasColumnType("integer");

                    b.Property<int>("ColumnOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxConcurrentSessions")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StateKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BoardId", "ColumnOrder")
                        .IsUnique()
                        .HasDatabaseName("IX_BoardColumns_BoardId_ColumnOrder");

                    b.HasIndex("BoardId", "StateKey")
                        .IsUnique()
                        .HasDatabaseName("IX_BoardColumns_BoardId_StateKey");

                    b.ToTable("BoardColumns", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.BoardWorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoardId", "IsActive")
                        .HasDatabaseName("IX_BoardWorkflowDefinitions_BoardId_IsActive");

                    b.HasIndex("BoardId", "Version")
                        .IsUnique()
                        .HasDatabaseName("IX_BoardWorkflowDefinitions_BoardId_Version");

                    b.ToTable("BoardWorkflowDefinitions", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveWorkflowRunId")
                        .HasColumnType("uuid");

                    b.Property<int?>("AgentQueuePosition")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AssignedAgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardColumnId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentWorktreeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LabelsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("OwnerSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TerminalReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActiveWorkflowRunId")
                        .IsUnique()
                        .HasDatabaseName("IX_Cards_ActiveWorkflowRunId");

                    b.HasIndex("AssignedAgentId")
                        .HasDatabaseName("IX_Cards_AssignedAgentId");

                    b.HasIndex("BoardColumnId")
                        .HasDatabaseName("IX_Cards_BoardColumnId");

                    b.HasIndex("BoardId")
                        .HasDatabaseName("IX_Cards_BoardId");

                    b.HasIndex("CurrentWorktreeId")
                        .HasDatabaseName("IX_Cards_CurrentWorktreeId");

                    b.HasIndex("OwnerSessionId")
                        .HasDatabaseName("IX_Cards_OwnerSessionId");

                    b.HasIndex("AssignedAgentId", "AgentQueuePosition")
                        .HasDatabaseName("IX_Cards_AssignedAgentId_AgentQueuePosition");

                    b.HasIndex("BoardId", "Identifier")
                        .IsUnique()
                        .HasDatabaseName("IX_Cards_BoardId_Identifier");

                    b.HasIndex("BoardId", "Status")
                        .HasDatabaseName("IX_Cards_BoardId_Status");

                    b.ToTable("Cards", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.CardWorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentStageId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkflowDefinitionSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("WorkflowTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("IX_CardWorkflowRuns_AgentId");

                    b.HasIndex("CardId")
                        .HasDatabaseName("IX_CardWorkflowRuns_CardId");

                    b.HasIndex("CurrentStageId");

                    b.HasIndex("WorkflowTemplateId");

                    b.HasIndex("CardId", "Id")
                        .IsUnique()
                        .HasDatabaseName("IX_CardWorkflowRuns_CardId_Id");

                    b.HasIndex("CardId", "Status")
                        .HasDatabaseName("IX_CardWorkflowRuns_CardId_Status");

                    b.ToTable("CardWorkflowRuns", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.CardWorkflowStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardWorkflowRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExecutorType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("GateRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ResultSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("StageOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SystemPrompt")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CardWorkflowRunId", "Id")
                        .IsUnique()
                        .HasDatabaseName("IX_CardWorkflowStages_RunId_Id");

                    b.HasIndex("CardWorkflowRunId", "StageOrder")
                        .IsUnique()
                        .HasDatabaseName("IX_CardWorkflowStages_RunId_StageOrder");

                    b.ToTable("CardWorkflowStages", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.ChatChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<int?>("AlertMinSeverity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("LastAuthor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastChannelMessageId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastMessagePreview")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("MessageCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReplyHandle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("ChatChannels", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.CostLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuditRecordId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("StageExecutionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid");

                    b.Property<long>("TokensIn")
                        .HasColumnType("bigint");

                    b.Property<long>("TokensOut")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuditRecordId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_CostLedgerEntries_CreatedAt");

                    b.HasIndex("StageExecutionId");

                    b.HasIndex("StageId")
                        .HasDatabaseName("IX_CostLedgerEntries_StageId");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("IX_CostLedgerEntries_WorkflowId");

                    b.ToTable("CostLedgerEntries", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.ExternalIssueRef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("TrackerKind")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique()
                        .HasDatabaseName("IX_ExternalIssueRefs_CardId");

                    b.HasIndex("TrackerKind", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_ExternalIssueRefs_TrackerKind_ExternalId");

                    b.ToTable("ExternalIssueRefs", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.GateDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DecidedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Feedback")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DecidedBy");

                    b.HasIndex("StageId")
                        .HasDatabaseName("IX_GateDecisions_StageId");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("IX_GateDecisions_WorkflowId");

                    b.ToTable("GateDecisions", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.LlmProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ProviderType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LlmProviders", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.ModelRouting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("WorkflowTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("WorkflowTemplateId", "StageName")
                        .IsUnique()
                        .HasDatabaseName("IX_ModelRoutings_WorkflowTemplateId_StageName");

                    b.ToTable("ModelRoutings", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseBranch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("master");

                    b.Property<string>("ConstitutionPath")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("AGENTS.md;CLAUDE.md;README.md");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("GitHubIntegrationEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("GitRepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LocalRepositoryPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.RetrySchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique()
                        .HasDatabaseName("IX_RetrySchedules_CardId");

                    b.HasIndex("NextRetryAt")
                        .HasDatabaseName("IX_RetrySchedules_NextRetryAt");

                    b.ToTable("RetrySchedules", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.RunAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BoardWorkflowDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastEventAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<string>("PhaseDurationsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("PhaseStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WorktreeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentSessionId")
                        .HasDatabaseName("IX_RunAttempts_AgentSessionId");

                    b.HasIndex("BoardWorkflowDefinitionId")
                        .HasDatabaseName("IX_RunAttempts_BoardWorkflowDefinitionId");

                    b.HasIndex("CardId")
                        .HasDatabaseName("IX_RunAttempts_CardId");

                    b.HasIndex("WorktreeId")
                        .HasDatabaseName("IX_RunAttempts_WorktreeId");

                    b.HasIndex("CardId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_RunAttempts_CardId_AttemptNumber");

                    b.ToTable("RunAttempts", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.SessionQueuedMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentSessionId", "Status", "Sequence")
                        .HasDatabaseName("IX_SessionQueuedMessages_AgentSessionId_Status_Sequence");

                    b.ToTable("SessionQueuedMessages", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Stage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExecutorType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("GateRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StageOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("IX_Stages_WorkflowId");

                    b.HasIndex("WorkflowId", "StageOrder")
                        .IsUnique()
                        .HasDatabaseName("IX_Stages_WorkflowId_StageOrder");

                    b.ToTable("Stages", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.StageExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<decimal>("EstimatedCostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("GitTagName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OutputContent")
                        .HasColumnType("text");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TokensIn")
                        .HasColumnType("bigint");

                    b.Property<long>("TokensOut")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StageId")
                        .HasDatabaseName("IX_StageExecutions_StageId");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("IX_StageExecutions_WorkflowId");

                    b.HasIndex("StageId", "Version")
                        .IsUnique()
                        .HasDatabaseName("IX_StageExecutions_StageId_Version");

                    b.ToTable("StageExecutions", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.TemplateGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_TemplateGroups_Name");

                    b.ToTable("TemplateGroups", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.TokenUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RunAttemptId")
                        .HasColumnType("uuid");

                    b.Property<long>("TokensIn")
                        .HasColumnType("bigint");

                    b.Property<long>("TokensOut")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RunAttemptId")
                        .IsUnique()
                        .HasDatabaseName("IX_TokenUsages_RunAttemptId");

                    b.ToTable("TokenUsages", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.TranscriptEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ParentUuid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Role")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("StopReason")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToolInput")
                        .HasColumnType("text");

                    b.Property<bool?>("ToolIsError")
                        .HasColumnType("boolean");

                    b.Property<string>("ToolName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ToolUseId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Uuid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AgentSessionId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("IX_TranscriptEntries_AgentSessionId_Sequence");

                    b.ToTable("TranscriptEntries", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@antiphon.local",
                            IsAdmin = true,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentStageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FeatureName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GitBranchName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("InitialContext")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurrentStageId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_Workflows_ProjectId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Workflows_Status");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("IX_Workflows_TemplateId");

                    b.HasIndex("ProjectId", "FeatureName")
                        .HasDatabaseName("IX_Workflows_ProjectId_FeatureName");

                    b.ToTable("Workflows", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.WorkflowTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("TemplateGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YamlDefinition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TemplateGroupId");

                    b.ToTable("WorkflowTemplates", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Worktree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseRef")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastTouchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RepoPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Branch")
                        .HasDatabaseName("IX_Worktrees_Branch");

                    b.HasIndex("CardId")
                        .HasDatabaseName("IX_Worktrees_CardId");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("IX_Worktrees_Path");

                    b.HasIndex("Status", "LastTouchedAt")
                        .HasDatabaseName("IX_Worktrees_Status_LastTouchedAt");

                    b.ToTable("Worktrees", (string)null);
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Agent", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Antiphon.Server.Domain.Entities.Card", "CurrentCard")
                        .WithMany()
                        .HasForeignKey("CurrentCardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Antiphon.Server.Domain.Entities.WorkflowTemplate", "DefaultWorkflowTemplate")
                        .WithMany()
                        .HasForeignKey("DefaultWorkflowTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Board");

                    b.Navigation("CurrentCard");

                    b.Navigation("DefaultWorkflowTemplate");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.AgentIncident", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.AgentSession", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.Card", "Card")
                        .WithMany("AgentSessions")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Antiphon.Server.Domain.Entities.Worktree", "Worktree")
                        .WithMany("AgentSessions")
                        .HasForeignKey("WorktreeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Card");

                    b.Navigation("Worktree");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.AgentSupervisionState", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.Agent", "Agent")
                        .WithOne()
                        .HasForeignKey("Antiphon.Server.Domain.Entities.AgentSupervisionState", "AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.ArtifactSectionReview", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.StageExecution", "StageExecution")
                        .WithMany()
                        .HasForeignKey("StageExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StageExecution");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.AuditRecord", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.StageExecution", "StageExecution")
                        .WithMany()
                        .HasForeignKey("StageExecutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Antiphon.Server.Domain.Entities.Stage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Antiphon.Server.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Antiphon.Server.Domain.Entities.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Stage");

                    b.Navigation("StageExecution");

                    b.Navigation("User");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Board", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.Project", "Project")
                        .WithMany("Boards")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.BoardColumn", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.Board", "Board")
                        .WithMany("Columns")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.BoardWorkflowDefinition", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.Board", "Board")
                        .WithMany("WorkflowDefinitions")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Card", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.CardWorkflowRun", "ActiveWorkflowRun")
                        .WithOne()
                        .HasForeignKey("Antiphon.Server.Domain.Entities.Card", "ActiveWorkflowRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Antiphon.Server.Domain.Entities.Agent", "AssignedAgent")
                        .WithMany("QueueCards")
                        .HasForeignKey("AssignedAgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Antiphon.Server.Domain.Entities.BoardColumn", "BoardColumn")
                        .WithMany("Cards")
                        .HasForeignKey("BoardColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Antiphon.Server.Domain.Entities.Board", "Board")
                        .WithMany("Cards")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Antiphon.Server.Domain.Entities.Worktree", "CurrentWorktree")
                        .WithMany()
                        .HasForeignKey("CurrentWorktreeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Antiphon.Server.Domain.Entities.AgentSession", "OwnerSession")
                        .WithMany()
                        .HasForeignKey("OwnerSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActiveWorkflowRun");

                    b.Navigation("AssignedAgent");

                    b.Navigation("Board");

                    b.Navigation("BoardColumn");

                    b.Navigation("CurrentWorktree");

                    b.Navigation("OwnerSession");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.CardWorkflowRun", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.Agent", "Agent")
                        .WithMany("WorkflowRuns")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Antiphon.Server.Domain.Entities.Card", "Card")
                        .WithMany("WorkflowRuns")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Antiphon.Server.Domain.Entities.CardWorkflowStage", "CurrentStage")
                        .WithMany()
                        .HasForeignKey("CurrentStageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Antiphon.Server.Domain.Entities.WorkflowTemplate", "WorkflowTemplate")
                        .WithMany()
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");

                    b.Navigation("Card");

                    b.Navigation("CurrentStage");

                    b.Navigation("WorkflowTemplate");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.CardWorkflowStage", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.CardWorkflowRun", "CardWorkflowRun")
                        .WithMany("Stages")
                        .HasForeignKey("CardWorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardWorkflowRun");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.ChatChannel", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.CostLedgerEntry", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.AuditRecord", "AuditRecord")
                        .WithMany()
                        .HasForeignKey("AuditRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Antiphon.Server.Domain.Entities.StageExecution", "StageExecution")
                        .WithMany()
                        .HasForeignKey("StageExecutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Antiphon.Server.Domain.Entities.Stage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Antiphon.Server.Domain.Entities.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditRecord");

                    b.Navigation("Stage");

                    b.Navigation("StageExecution");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.ExternalIssueRef", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.Card", "Card")
                        .WithOne("ExternalIssueRef")
                        .HasForeignKey("Antiphon.Server.Domain.Entities.ExternalIssueRef", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.GateDecision", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.User", "DecidedByUser")
                        .WithMany()
                        .HasForeignKey("DecidedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Antiphon.Server.Domain.Entities.Stage", "Stage")
                        .WithMany("GateDecisions")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Antiphon.Server.Domain.Entities.Workflow", "Workflow")
                        .WithMany("GateDecisions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DecidedByUser");

                    b.Navigation("Stage");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.ModelRouting", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.LlmProvider", "Provider")
                        .WithMany("ModelRoutings")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Antiphon.Server.Domain.Entities.WorkflowTemplate", "WorkflowTemplate")
                        .WithMany()
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Provider");

                    b.Navigation("WorkflowTemplate");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.RetrySchedule", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.Card", "Card")
                        .WithOne("RetrySchedule")
                        .HasForeignKey("Antiphon.Server.Domain.Entities.RetrySchedule", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.RunAttempt", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.AgentSession", "AgentSession")
                        .WithMany("RunAttempts")
                        .HasForeignKey("AgentSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Antiphon.Server.Domain.Entities.BoardWorkflowDefinition", "BoardWorkflowDefinition")
                        .WithMany()
                        .HasForeignKey("BoardWorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Antiphon.Server.Domain.Entities.Card", "Card")
                        .WithMany("RunAttempts")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Antiphon.Server.Domain.Entities.Worktree", "Worktree")
                        .WithMany("RunAttempts")
                        .HasForeignKey("WorktreeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AgentSession");

                    b.Navigation("BoardWorkflowDefinition");

                    b.Navigation("Card");

                    b.Navigation("Worktree");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.SessionQueuedMessage", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.AgentSession", "AgentSession")
                        .WithMany()
                        .HasForeignKey("AgentSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentSession");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Stage", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.Workflow", "Workflow")
                        .WithMany("Stages")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.StageExecution", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.Stage", "Stage")
                        .WithMany("StageExecutions")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Antiphon.Server.Domain.Entities.Workflow", "Workflow")
                        .WithMany("StageExecutions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Stage");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.TokenUsage", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.RunAttempt", "RunAttempt")
                        .WithOne("TokenUsage")
                        .HasForeignKey("Antiphon.Server.Domain.Entities.TokenUsage", "RunAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RunAttempt");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.TranscriptEntry", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.AgentSession", "AgentSession")
                        .WithMany()
                        .HasForeignKey("AgentSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentSession");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Workflow", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.Stage", "CurrentStage")
                        .WithMany()
                        .HasForeignKey("CurrentStageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Antiphon.Server.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Antiphon.Server.Domain.Entities.WorkflowTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentStage");

                    b.Navigation("Project");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.WorkflowTemplate", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.TemplateGroup", "TemplateGroup")
                        .WithMany("Templates")
                        .HasForeignKey("TemplateGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TemplateGroup");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Worktree", b =>
                {
                    b.HasOne("Antiphon.Server.Domain.Entities.Card", "Card")
                        .WithMany("Worktrees")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Agent", b =>
                {
                    b.Navigation("QueueCards");

                    b.Navigation("WorkflowRuns");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.AgentSession", b =>
                {
                    b.Navigation("RunAttempts");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Board", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Columns");

                    b.Navigation("WorkflowDefinitions");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.BoardColumn", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Card", b =>
                {
                    b.Navigation("AgentSessions");

                    b.Navigation("ExternalIssueRef");

                    b.Navigation("RetrySchedule");

                    b.Navigation("RunAttempts");

                    b.Navigation("WorkflowRuns");

                    b.Navigation("Worktrees");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.CardWorkflowRun", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.LlmProvider", b =>
                {
                    b.Navigation("ModelRoutings");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Project", b =>
                {
                    b.Navigation("Boards");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.RunAttempt", b =>
                {
                    b.Navigation("TokenUsage");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Stage", b =>
                {
                    b.Navigation("GateDecisions");

                    b.Navigation("StageExecutions");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.TemplateGroup", b =>
                {
                    b.Navigation("Templates");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Workflow", b =>
                {
                    b.Navigation("GateDecisions");

                    b.Navigation("StageExecutions");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Antiphon.Server.Domain.Entities.Worktree", b =>
                {
                    b.Navigation("AgentSessions");

                    b.Navigation("RunAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
