<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Antiphon.MarkdownPdf.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.41.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.*" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.*" />
  </ItemGroup>
</Project>
